spring:
  data:
    mongodb:
      uri=mongodb://localhost:27017/mydb:
#  datasource:
#    url: jdbc:h2:mem:maindb
#  sql:
#    init:
#      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: none